baseURL = "http://pollex.club/"
languageCode = "en-us"
title = "Pollex"
sectionPagesMenu = "nav"
theme = "pollex"

[[menu.nav]]
    identifier = "board"
    name = "Board"
    url = "/board"
    weight = 2
[[menu.nav]]
    identifier = "rules"
    name = "Rules"
    url = "/rules"
    weight = 3
[[menu.nav]]
    identifier = "contact"
    name = "Contact & join"
    url = "/contact"
    weight = 4
[[menu.nav]]
    identifier = "events"
    name = "Events"
    url = "/events"
    weight = 1
[[menu.nav]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 5