
name = "Pollex"
license = "MIT"
licenselink = "https://github.com/Juhannuspukki/pollex-web-17/tree/master/themes/pollex/LICENSE.md"
description = ""
homepage = "pollex.club"
tags = []
features = []
min_version = "0.27.1"